In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

%matplotlib inline

In [4]:
IRS_data = pd.read_csv('/Users/chrislele/Downloads/IRSIncomeByZipCode.csv')

In [5]:
IRS_data.head()

,STATE,ZIPCODE,Number of returns,Adjusted gross income (AGI),Avg AGI,Number of returns with total income,Total income amount,Avg total income,Number of returns with taxable income,Taxable income amount,Avg taxable income
0,AL,0,2022380,105089761,51.963410,2022380,106420533,52.621433,1468370,67850874,46.208295
1,AL,35004,4930,255534,51.832454,4930,258024,52.337525,4020,163859,40.760945
2,AL,35005,3300,128387,38.905152,3300,129390,39.209091,2440,70760,29.000000
3,AL,35006,1230,58302,47.400000,1230,58585,47.630081,940,36341,38.660638
4,AL,35007,11990,643708,53.687073,11990,651350,54.324437,9280,414878,44.706681

In [6]:
SAT_info = pd.read_csv('/Users/chrislele/Downloads/scores.csv')

In [7]:
SAT_info.T

,0,1,2,3,4,5,6,7,8,9,...,425,426,427,428,429,430,431,432,433,434
School ID,02M260,06M211,01M539,02M294,02M308,02M545,01M292,01M696,02M305,01M509,...,28Q690,29Q327,27Q400,27Q260,27Q309,27Q302,27Q324,27Q262,27Q351,27Q323
School Name,Clinton School Writers and Artists,Inwood Early College for Health and Informatio...,"New Explorations into Science, Technology and ...",Essex Street Academy,Lower Manhattan Arts Academy,High School for Dual Language and Asian Studies,Henry Street School for International Studies,Bard High School Early College,Urban Assembly Academy of Government and Law,Marta Valle High School,...,High School for Law Enforcement and Public Safety,Eagle Academy for Young Men III,August Martin High School,Frederick Douglass Academy VI High School,Academy of Medical Technology (College Board),"Queens High School for Information, Research, ...",Rockaway Park High School for Environmental Su...,Channel View School for Research,Rockaway Collegiate High School,Scholars' Academy
Borough,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens
Building Code,M933,M052,M022,M445,M445,M445,M056,M097,M445,M025,...,Q690,Q633,Q400,Q465,Q465,Q465,Q410,Q410,Q410,Q180
Street Address,425 West 33rd Street,650 Academy Street,111 Columbia Street,350 Grand Street,350 Grand Street,350 Grand Street,220 Henry Street,525 East Houston Street,350 Grand Street,145 Stanton Street,...,116-25 Guy R Brewer Boulevard,171-10 Linden Boulevard,156-10 Baisley Boulevard,8-21 Bay 25th Street,8-21 Bay 25th Street,8-21 Bay 25th Street,100-00 Beach Channel Drive,100-00 Beach Channel Drive,100-00 Beach Channel Drive,320 Beach 104th Street
City,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Jamaica,Jamaica,Jamaica,Far Rockaway,Far Rockaway,Far Rockaway,Rockaway Park,Rockaway Park,Rockaway Park,Rockaway Park
State,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY,...,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY
Zip Code,10001,10002,10002,10002,10002,10002,10002,10002,10002,10002,...,11434,11434,11434,11691,11691,11691,11694,11694,11694,11694
Latitude,40.75321,40.86605,40.71873,40.71687,40.71687,40.71687,40.71376,40.71896,40.71687,40.72057,...,40.68618,40.69167,40.67553,40.60199,40.60199,40.60199,40.58601,40.58601,40.58601,40.58413
Longitude,-73.99786,-73.92486,-73.97943,-73.98953,-73.98953,-73.98953,-73.98526,-73.97607,-73.98953,-73.98567,...,-73.78408,-73.77903,-73.78343,-73.76283,-73.76283,-73.76283,-73.82309,-73.82309,-73.82309,-73.82568
Phone Number,212-695-9114,718-935-3660,212-677-5190,212-475-4773,212-505-0143,212-475-4097,212-406-9411,212-995-8479,212-505-0745,212-473-8152,...,718-977-4800,718-480-2600,718-528-2920,718-471-2154,718-471-3571,718-868-2978,718-734-3280,718-634-1970,718-734-3290,718-474-6918
Start Time,NaN,8:30 AM,8:15 AM,8:00 AM,8:30 AM,8:00 AM,8:30 AM,9:00 AM,8:32 AM,8:00 AM,...,8:00 AM,8:45 AM,8:00 AM,7:45 AM,8:00 AM,7:45 AM,8:45 AM,8:15 AM,8:30 AM,8:45 AM
End Time,NaN,3:00 PM,4:00 PM,2:45 PM,3:00 PM,3:35 PM,3:30 PM,3:50 PM,3:45 PM,3:30 PM,...,3:00 PM,4:45 PM,3:30 PM,2:05 PM,3:15 PM,4:10 PM,3:30 PM,3:04 PM,4:20 PM,3:00 PM
Student Enrollment,NaN,87.0,1735.0,358.0,383.0,416.0,255.0,545.0,329.0,363.0,...,604.0,428.0,679.0,409.0,637.0,381.0,368.0,683.0,397.0,1302.0
Percent White,NaN,3.4%,28.6%,11.7%,3.1%,1.7%,3.9%,45.3%,2.7%,2.5%,...,1.8%,1.8%,1.5%,0.7%,2.7%,2.1%,14.7%,10.7%,3.8%,34.7%
Percent Black,NaN,21.8%,13.3%,38.5%,28.2%,3.1%,24.4%,17.2%,41.9%,39.9%,...,66.4%,86.3%,75.4%,59.7%,50.1%,49.1%,46.7%,53.2%,52.6%,22.7%
Percent Hispanic,NaN,67.8%,18.0%,41.3%,56.9%,5.5%,56.6%,18.7%,49.2%,51.2%,...,18.9%,5.4%,13.0%,37.9%,37.7%,43.6%,30.2%,29.1%,33.5%,19.6%
Percent Asian,NaN,4.6%,38.5%,5.9%,8.6%,88.9%,13.2%,17.1%,5.8%,5.8%,...,10.4%,0.6%,7.5%,1.5%,6.6%,4.2%,3.5%,6.0%,5.0%,21.4%
Average Score (SAT Math),NaN,NaN,657.0,395.0,418.0,613.0,410.0,634.0,389.0,438.0,...,410.0,NaN,366.0,410.0,422.0,372.0,357.0,427.0,399.0,588.0
Average Score (SAT Reading),NaN,NaN,601.0,411.0,428.0,453.0,406.0,641.0,395.0,413.0,...,431.0,NaN,372.0,418.0,424.0,362.0,381.0,430.0,403.0,560.0
Average Score (SAT Writing),NaN,NaN,601.0,387.0,415.0,463.0,381.0,639.0,381.0,394.0,...,409.0,NaN,364.0,407.0,415.0,352.0,376.0,423.0,405.0,568.0
Percent Tested,NaN,NaN,91.0%,78.9%,65.1%,95.9%,59.7%,70.8%,80.8%,35.6%,...,56.6%,NaN,26.3%,30.1%,67.6%,44.6%,38.5%,76.6%,46.5%,99.2%

In [8]:
nyc_zipcodes = SAT_info['Zip Code'].unique()

filtered_irs_data = IRS_data[IRS_data['ZIPCODE'].isin(nyc_zipcodes)][['ZIPCODE', 'Avg total income']]
filtered_irs_data.rename(columns={'ZIPCODE': 'Zip Code'}, inplace=True)

merged_data = SAT_info.merge(filtered_irs_data, on='Zip Code', how='left')

In [9]:
merged_data.T

,0,1,2,3,4,5,6,7,8,9,...,425,426,427,428,429,430,431,432,433,434
School ID,02M260,06M211,01M539,02M294,02M308,02M545,01M292,01M696,02M305,01M509,...,28Q690,29Q327,27Q400,27Q260,27Q309,27Q302,27Q324,27Q262,27Q351,27Q323
School Name,Clinton School Writers and Artists,Inwood Early College for Health and Informatio...,"New Explorations into Science, Technology and ...",Essex Street Academy,Lower Manhattan Arts Academy,High School for Dual Language and Asian Studies,Henry Street School for International Studies,Bard High School Early College,Urban Assembly Academy of Government and Law,Marta Valle High School,...,High School for Law Enforcement and Public Safety,Eagle Academy for Young Men III,August Martin High School,Frederick Douglass Academy VI High School,Academy of Medical Technology (College Board),"Queens High School for Information, Research, ...",Rockaway Park High School for Environmental Su...,Channel View School for Research,Rockaway Collegiate High School,Scholars' Academy
Borough,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens
Building Code,M933,M052,M022,M445,M445,M445,M056,M097,M445,M025,...,Q690,Q633,Q400,Q465,Q465,Q465,Q410,Q410,Q410,Q180
Street Address,425 West 33rd Street,650 Academy Street,111 Columbia Street,350 Grand Street,350 Grand Street,350 Grand Street,220 Henry Street,525 East Houston Street,350 Grand Street,145 Stanton Street,...,116-25 Guy R Brewer Boulevard,171-10 Linden Boulevard,156-10 Baisley Boulevard,8-21 Bay 25th Street,8-21 Bay 25th Street,8-21 Bay 25th Street,100-00 Beach Channel Drive,100-00 Beach Channel Drive,100-00 Beach Channel Drive,320 Beach 104th Street
City,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Jamaica,Jamaica,Jamaica,Far Rockaway,Far Rockaway,Far Rockaway,Rockaway Park,Rockaway Park,Rockaway Park,Rockaway Park
State,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY,...,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY
Zip Code,10001,10002,10002,10002,10002,10002,10002,10002,10002,10002,...,11434,11434,11434,11691,11691,11691,11694,11694,11694,11694
Latitude,40.75321,40.86605,40.71873,40.71687,40.71687,40.71687,40.71376,40.71896,40.71687,40.72057,...,40.68618,40.69167,40.67553,40.60199,40.60199,40.60199,40.58601,40.58601,40.58601,40.58413
Longitude,-73.99786,-73.92486,-73.97943,-73.98953,-73.98953,-73.98953,-73.98526,-73.97607,-73.98953,-73.98567,...,-73.78408,-73.77903,-73.78343,-73.76283,-73.76283,-73.76283,-73.82309,-73.82309,-73.82309,-73.82568
Phone Number,212-695-9114,718-935-3660,212-677-5190,212-475-4773,212-505-0143,212-475-4097,212-406-9411,212-995-8479,212-505-0745,212-473-8152,...,718-977-4800,718-480-2600,718-528-2920,718-471-2154,718-471-3571,718-868-2978,718-734-3280,718-634-1970,718-734-3290,718-474-6918
Start Time,NaN,8:30 AM,8:15 AM,8:00 AM,8:30 AM,8:00 AM,8:30 AM,9:00 AM,8:32 AM,8:00 AM,...,8:00 AM,8:45 AM,8:00 AM,7:45 AM,8:00 AM,7:45 AM,8:45 AM,8:15 AM,8:30 AM,8:45 AM
End Time,NaN,3:00 PM,4:00 PM,2:45 PM,3:00 PM,3:35 PM,3:30 PM,3:50 PM,3:45 PM,3:30 PM,...,3:00 PM,4:45 PM,3:30 PM,2:05 PM,3:15 PM,4:10 PM,3:30 PM,3:04 PM,4:20 PM,3:00 PM
Student Enrollment,NaN,87.0,1735.0,358.0,383.0,416.0,255.0,545.0,329.0,363.0,...,604.0,428.0,679.0,409.0,637.0,381.0,368.0,683.0,397.0,1302.0
Percent White,NaN,3.4%,28.6%,11.7%,3.1%,1.7%,3.9%,45.3%,2.7%,2.5%,...,1.8%,1.8%,1.5%,0.7%,2.7%,2.1%,14.7%,10.7%,3.8%,34.7%
Percent Black,NaN,21.8%,13.3%,38.5%,28.2%,3.1%,24.4%,17.2%,41.9%,39.9%,...,66.4%,86.3%,75.4%,59.7%,50.1%,49.1%,46.7%,53.2%,52.6%,22.7%
Percent Hispanic,NaN,67.8%,18.0%,41.3%,56.9%,5.5%,56.6%,18.7%,49.2%,51.2%,...,18.9%,5.4%,13.0%,37.9%,37.7%,43.6%,30.2%,29.1%,33.5%,19.6%
Percent Asian,NaN,4.6%,38.5%,5.9%,8.6%,88.9%,13.2%,17.1%,5.8%,5.8%,...,10.4%,0.6%,7.5%,1.5%,6.6%,4.2%,3.5%,6.0%,5.0%,21.4%
Average Score (SAT Math),NaN,NaN,657.0,395.0,418.0,613.0,410.0,634.0,389.0,438.0,...,410.0,NaN,366.0,410.0,422.0,372.0,357.0,427.0,399.0,588.0
Average Score (SAT Reading),NaN,NaN,601.0,411.0,428.0,453.0,406.0,641.0,395.0,413.0,...,431.0,NaN,372.0,418.0,424.0,362.0,381.0,430.0,403.0,560.0
Average Score (SAT Writing),NaN,NaN,601.0,387.0,415.0,463.0,381.0,639.0,381.0,394.0,...,409.0,NaN,364.0,407.0,415.0,352.0,376.0,423.0,405.0,568.0
Percent Tested,NaN,NaN,91.0%,78.9%,65.1%,95.9%,59.7%,70.8%,80.8%,35.6%,...,56.6%,NaN,26.3%,30.1%,67.6%,44.6%,38.5%,76.6%,46.5%,99.2%
Avg total income,155.101676,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,...,39.71418,39.71418,39.71418,37.844035,37.844035,37.844035,91.24427,91.24427,91.24427,91.24427

In [10]:
missing = pd.concat([merged_data.isnull().sum(), 100 * merged_data.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending=False)

                             count          %
Average Score (SAT Writing)     60  13.793103
Average Score (SAT Reading)     60  13.793103
Average Score (SAT Math)        60  13.793103
Percent Tested                  49  11.264368
Percent Asian                    7   1.609195
Percent Hispanic                 7   1.609195
Percent Black                    7   1.609195
Percent White                    7   1.609195
Student Enrollment               7   1.609195
Start Time                       4   0.919540
End Time                         4   0.919540
School ID                        0   0.000000
School Name                      0   0.000000
Phone Number                     0   0.000000
Longitude                        0   0.000000
Latitude                         0   0.000000
Zip Code                         0   0.000000
State                            0   0.000000
City                             0   0.000000
Street Address                   0   0.000000
Building Code                    0   0.000000
Borough                          0   0.000000
Avg total income                 0   0.000000

In [11]:
NYC_Housing = pd.read_csv('/Users/chrislele/Downloads/NYC Housing Sales.csv')

In [12]:
NYC_Housing.head()

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,5,0,5,1633,6440,1900,2,C2,6625000,2017-07-19 00:00:00
1,5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,...,28,3,31,4616,18690,1900,2,C7,-,2016-12-14 00:00:00
2,6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,...,16,1,17,2212,7803,1900,2,C7,-,2016-12-09 00:00:00
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,10,0,10,2272,6794,1913,2,C4,3936272,2016-09-23 00:00:00
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,6,0,6,2369,4615,1900,2,C2,8000000,2016-11-17 00:00:00

In [13]:
NYC_Housing.columns

Index(['Unnamed: 0', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE',
       'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE PRICE', 'SALE DATE'],
      dtype='object')

In [14]:
import numpy as np

# Replace '-' with NaN
NYC_Housing['SALE PRICE'] = NYC_Housing['SALE PRICE'].replace('-', np.nan)

# Count non-null values
non_null_values = NYC_Housing['SALE PRICE'].notnull().sum()

# Count null values
null_values = len(NYC_Housing) - non_null_values

print("Number of null values in 'SALE PRICE':", null_values)

Number of null values in 'SALE PRICE': 0

In [15]:
# Convert 'SALE PRICE' column to numeric type
NYC_Housing['SALE PRICE'] = pd.to_numeric(NYC_Housing['SALE PRICE'], errors='coerce')

# Count values greater than 1000 in 'SALE PRICE' column
count_greater_than_1000 = len(NYC_Housing[NYC_Housing['SALE PRICE'] > 1000])

print("Number of values greater than 1000 in 'SALE PRICE':", count_greater_than_1000)

Number of values greater than 1000 in 'SALE PRICE': 58604

In [16]:
# Convert 'SALE PRICE' column to numeric type
NYC_Housing['GROSS SQUARE FEET'] = pd.to_numeric(NYC_Housing['GROSS SQUARE FEET'], errors='coerce')

# Count values greater than 1000 in 'SALE PRICE' column
count_greater_than_100 = len(NYC_Housing[NYC_Housing['GROSS SQUARE FEET'] > 100])

print("Number of values greater than 100 in 'GROSS SQUARE FEET':", count_greater_than_100)

Number of values greater than 100 in 'GROSS SQUARE FEET': 45514

In [17]:
# Convert 'SALE PRICE' and 'GROSS SQUARE FEET' columns to numeric type
NYC_Housing['SALE PRICE'] = pd.to_numeric(NYC_Housing['SALE PRICE'], errors='coerce')
NYC_Housing['GROSS SQUARE FEET'] = pd.to_numeric(NYC_Housing['GROSS SQUARE FEET'], errors='coerce')

# Create 'Avg_price_sqft' column by dividing 'SALE PRICE' by 'GROSS SQUARE FEET'
NYC_Housing['Avg_price_sqft'] = NYC_Housing['SALE PRICE'] / NYC_Housing['GROSS SQUARE FEET']

In [18]:
NYC_Housing['Avg_price_sqft'].info

<bound method Series.info of 0        1028.726708
1                NaN
2                NaN
3         579.374742
4        1733.477790
            ...
84543     174.757282
84544     231.384098
84545     307.486631
84546     182.374986
84547      28.875000
Name: Avg_price_sqft, Length: 84548, dtype: float64>

In [19]:
# Remove NaN values from 'Avg_price_sqft' column
NYC_Housing_cleaned = NYC_Housing.dropna(subset=['Avg_price_sqft'])

# View head of cleaned DataFrame
NYC_Housing_cleaned['Avg_price_sqft'].head(50)

0      1028.726708
3       579.374742
4      1733.477790
6       755.522953
9       876.315932
11      838.056680
22      709.346686
73      767.712218
172     982.142857
173    1286.554922
174    1279.288985
195    1031.790296
206    1926.070039
207       0.001769
208       0.001769
209       0.001769
212    1556.850141
214    2228.187919
216    4253.056885
218    2058.823529
219    1638.888889
220    2629.848784
221    1079.963235
222     250.211690
223      65.843602
224      99.584518
227    3442.622951
230     843.137255
231     868.192581
232     965.575147
233     850.000000
234     231.248743
239      29.689600
277      23.114754
831    2025.228325
832       0.002995
834    1855.183270
928    4240.196078
929    3016.505407
931    1326.705701
932     990.243902
937    1360.759494
938    2255.866206
940    5263.157895
941    2715.189873
943    2481.854367
945     933.333333
947    2305.064322
949     726.088583
950    1143.075690
Name: Avg_price_sqft, dtype: float64

In [20]:
NYC_Housing_filtered = NYC_Housing[NYC_Housing['Avg_price_sqft'] >= 20]
NYC_Housing_filtered.head(100)

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,Avg_price_sqft
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,0,5,1633,6440.0,1900,2,C2,6625000.0,2017-07-19 00:00:00,1028.726708
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,0,10,2272,6794.0,1913,2,C4,3936272.0,2016-09-23 00:00:00,579.374742
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,0,6,2369,4615.0,1900,2,C2,8000000.0,2016-11-17 00:00:00,1733.477790
6,10,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,406,32,,C4,210 AVENUE B,...,0,8,1750,4226.0,1920,2,C4,3192840.0,2016-09-23 00:00:00,755.522953
9,13,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,387,153,,D9,629 EAST 5TH STREET,...,0,24,4489,18523.0,1920,2,D9,16232000.0,2016-11-07 00:00:00,876.315932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2050,2054,1,FASHION,21 OFFICE BUILDINGS,4,833,11,,O4,1250 BROADWAY,...,55,55,30750,645977.0,1969,4,O4,565000000.0,2016-11-01 00:00:00,874.644144
2051,2055,1,FASHION,21 OFFICE BUILDINGS,4,838,12,,O6,53 WEST 36TH STREET,...,17,17,5925,64300.0,1911,4,O6,54000000.0,2016-10-27 00:00:00,839.813375
2058,2062,1,FASHION,23 LOFT BUILDINGS,4,762,61,,L1,338 WEST 39TH STREET,...,12,12,4937,55473.0,1926,4,L1,1161500.0,2017-07-21 00:00:00,20.938114
2059,2063,1,FASHION,23 LOFT BUILDINGS,4,785,75,,L3,260 WEST 36TH STREET,...,12,12,7266,81375.0,1907,4,L3,5000000.0,2017-02-09 00:00:00,61.443932
2064,2068,1,FASHION,25 LUXURY HOTELS,4,760,18,,H2,341 WEST 36TH STREET,...,1,1,7406,81000.0,2007,4,H2,105592700.0,2017-08-16 00:00:00,1303.613580

In [21]:
print(merged_data.columns)
print(NYC_Housing.columns)

Index(['School ID', 'School Name', 'Borough', 'Building Code',
       'Street Address', 'City', 'State', 'Zip Code', 'Latitude', 'Longitude',
       'Phone Number', 'Start Time', 'End Time', 'Student Enrollment',
       'Percent White', 'Percent Black', 'Percent Hispanic', 'Percent Asian',
       'Average Score (SAT Math)', 'Average Score (SAT Reading)',
       'Average Score (SAT Writing)', 'Percent Tested', 'Avg total income'],
      dtype='object')
Index(['Unnamed: 0', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE',
       'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE PRICE', 'SALE DATE', 'Avg_price_sqft'],
      dtype='object')

In [22]:
# Check the existing column names in NYC_Housing DataFrame
print(NYC_Housing.columns)

Index(['Unnamed: 0', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE',
       'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE PRICE', 'SALE DATE', 'Avg_price_sqft'],
      dtype='object')

In [23]:
NYC_Housing.head(2).T

,0,1
Unnamed: 0,4,5
BOROUGH,1,1
NEIGHBORHOOD,ALPHABET CITY,ALPHABET CITY
BUILDING CLASS CATEGORY,07 RENTALS - WALKUP APARTMENTS,07 RENTALS - WALKUP APARTMENTS
TAX CLASS AT PRESENT,2A,2
BLOCK,392,399
LOT,6,26
EASE-MENT,,
BUILDING CLASS AT PRESENT,C2,C7
ADDRESS,153 AVENUE B,234 EAST 4TH STREET
APARTMENT NUMBER,,
ZIP CODE,10009,10009
RESIDENTIAL UNITS,5,28
COMMERCIAL UNITS,0,3
TOTAL UNITS,5,31
LAND SQUARE FEET,1633,4616
GROSS SQUARE FEET,6440.0,18690.0
YEAR BUILT,1900,1900
TAX CLASS AT TIME OF SALE,2,2
BUILDING CLASS AT TIME OF SALE,C2,C7
SALE PRICE,6625000.0,NaN
SALE DATE,2017-07-19 00:00:00,2016-12-14 00:00:00
Avg_price_sqft,1028.726708,NaN

In [24]:
# Rename 'ZIP CODE' column to 'Zip Code' in NYC_Housing
NYC_Housing.rename(columns={'ZIP CODE': 'Zip Code'}, inplace=True)

In [25]:
display(NYC_Housing.columns, merged_data.columns)

Index(['Unnamed: 0', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'Zip Code',
       'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE PRICE', 'SALE DATE', 'Avg_price_sqft'],
      dtype='object')

Index(['School ID', 'School Name', 'Borough', 'Building Code',
       'Street Address', 'City', 'State', 'Zip Code', 'Latitude', 'Longitude',
       'Phone Number', 'Start Time', 'End Time', 'Student Enrollment',
       'Percent White', 'Percent Black', 'Percent Hispanic', 'Percent Asian',
       'Average Score (SAT Math)', 'Average Score (SAT Reading)',
       'Average Score (SAT Writing)', 'Percent Tested', 'Avg total income'],
      dtype='object')

In [26]:
# Select columns from NYC_Housing
columns_to_merge = ['BUILDING CLASS AT PRESENT', 'TOTAL UNITS', 'Zip Code','GROSS SQUARE FEET', 'SALE PRICE', 'SALE DATE', 'Avg_price_sqft']

# Merge DataFrames
#merged_data = merged_data.merge(NYC_Housing[columns_to_merge], on='Zip Code', how='left')

md = merged_data.merge(NYC_Housing[columns_to_merge].groupby('Zip Code').median().reset_index(), on='Zip Code', how='left')

# View head of the merged DataFrame
#merged_data.head()
md.T

,0,1,2,3,4,5,6,7,8,9,...,425,426,427,428,429,430,431,432,433,434
School ID,02M260,06M211,01M539,02M294,02M308,02M545,01M292,01M696,02M305,01M509,...,28Q690,29Q327,27Q400,27Q260,27Q309,27Q302,27Q324,27Q262,27Q351,27Q323
School Name,Clinton School Writers and Artists,Inwood Early College for Health and Informatio...,"New Explorations into Science, Technology and ...",Essex Street Academy,Lower Manhattan Arts Academy,High School for Dual Language and Asian Studies,Henry Street School for International Studies,Bard High School Early College,Urban Assembly Academy of Government and Law,Marta Valle High School,...,High School for Law Enforcement and Public Safety,Eagle Academy for Young Men III,August Martin High School,Frederick Douglass Academy VI High School,Academy of Medical Technology (College Board),"Queens High School for Information, Research, ...",Rockaway Park High School for Environmental Su...,Channel View School for Research,Rockaway Collegiate High School,Scholars' Academy
Borough,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens
Building Code,M933,M052,M022,M445,M445,M445,M056,M097,M445,M025,...,Q690,Q633,Q400,Q465,Q465,Q465,Q410,Q410,Q410,Q180
Street Address,425 West 33rd Street,650 Academy Street,111 Columbia Street,350 Grand Street,350 Grand Street,350 Grand Street,220 Henry Street,525 East Houston Street,350 Grand Street,145 Stanton Street,...,116-25 Guy R Brewer Boulevard,171-10 Linden Boulevard,156-10 Baisley Boulevard,8-21 Bay 25th Street,8-21 Bay 25th Street,8-21 Bay 25th Street,100-00 Beach Channel Drive,100-00 Beach Channel Drive,100-00 Beach Channel Drive,320 Beach 104th Street
City,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Jamaica,Jamaica,Jamaica,Far Rockaway,Far Rockaway,Far Rockaway,Rockaway Park,Rockaway Park,Rockaway Park,Rockaway Park
State,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY,...,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY
Zip Code,10001,10002,10002,10002,10002,10002,10002,10002,10002,10002,...,11434,11434,11434,11691,11691,11691,11694,11694,11694,11694
Latitude,40.75321,40.86605,40.71873,40.71687,40.71687,40.71687,40.71376,40.71896,40.71687,40.72057,...,40.68618,40.69167,40.67553,40.60199,40.60199,40.60199,40.58601,40.58601,40.58601,40.58413
Longitude,-73.99786,-73.92486,-73.97943,-73.98953,-73.98953,-73.98953,-73.98526,-73.97607,-73.98953,-73.98567,...,-73.78408,-73.77903,-73.78343,-73.76283,-73.76283,-73.76283,-73.82309,-73.82309,-73.82309,-73.82568
Phone Number,212-695-9114,718-935-3660,212-677-5190,212-475-4773,212-505-0143,212-475-4097,212-406-9411,212-995-8479,212-505-0745,212-473-8152,...,718-977-4800,718-480-2600,718-528-2920,718-471-2154,718-471-3571,718-868-2978,718-734-3280,718-634-1970,718-734-3290,718-474-6918
Start Time,NaN,8:30 AM,8:15 AM,8:00 AM,8:30 AM,8:00 AM,8:30 AM,9:00 AM,8:32 AM,8:00 AM,...,8:00 AM,8:45 AM,8:00 AM,7:45 AM,8:00 AM,7:45 AM,8:45 AM,8:15 AM,8:30 AM,8:45 AM
End Time,NaN,3:00 PM,4:00 PM,2:45 PM,3:00 PM,3:35 PM,3:30 PM,3:50 PM,3:45 PM,3:30 PM,...,3:00 PM,4:45 PM,3:30 PM,2:05 PM,3:15 PM,4:10 PM,3:30 PM,3:04 PM,4:20 PM,3:00 PM
Student Enrollment,NaN,87.0,1735.0,358.0,383.0,416.0,255.0,545.0,329.0,363.0,...,604.0,428.0,679.0,409.0,637.0,381.0,368.0,683.0,397.0,1302.0
Percent White,NaN,3.4%,28.6%,11.7%,3.1%,1.7%,3.9%,45.3%,2.7%,2.5%,...,1.8%,1.8%,1.5%,0.7%,2.7%,2.1%,14.7%,10.7%,3.8%,34.7%
Percent Black,NaN,21.8%,13.3%,38.5%,28.2%,3.1%,24.4%,17.2%,41.9%,39.9%,...,66.4%,86.3%,75.4%,59.7%,50.1%,49.1%,46.7%,53.2%,52.6%,22.7%
Percent Hispanic,NaN,67.8%,18.0%,41.3%,56.9%,5.5%,56.6%,18.7%,49.2%,51.2%,...,18.9%,5.4%,13.0%,37.9%,37.7%,43.6%,30.2%,29.1%,33.5%,19.6%
Percent Asian,NaN,4.6%,38.5%,5.9%,8.6%,88.9%,13.2%,17.1%,5.8%,5.8%,...,10.4%,0.6%,7.5%,1.5%,6.6%,4.2%,3.5%,6.0%,5.0%,21.4%
Average Score (SAT Math),NaN,NaN,657.0,395.0,418.0,613.0,410.0,634.0,389.0,438.0,...,410.0,NaN,366.0,410.0,422.0,372.0,357.0,427.0,399.0,588.0
Average Score (SAT Reading),NaN,NaN,601.0,411.0,428.0,453.0,406.0,641.0,395.0,413.0,...,431.0,NaN,372.0,418.0,424.0,362.0,381.0,430.0,403.0,560.0
Average Score (SAT Writing),NaN,NaN,601.0,387.0,415.0,463.0,381.0,639.0,381.0,394.0,...,409.0,NaN,364.0,407.0,415.0,352.0,376.0,423.0,405.0,568.0
Percent Tested,NaN,NaN,91.0%,78.9%,65.1%,95.9%,59.7%,70.8%,80.8%,35.6%,...,56.6%,NaN,26.3%,30.1%,67.6%,44.6%,38.5%,76.6%,46.5%,99.2%
Avg total income,155.101676,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,...,39.71418,39.71418,39.71418,37.844035,37.844035,37.844035,91.24427,91.24427,91.24427,91.24427
TOTAL UNITS,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0
GROSS SQUARE FEET,19453.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,...,1378.0,1378.0,1378.0,2080.0,2080.0,2080.0,2115.0,2115.0,2115.0,2115.0
SALE PRICE,1750000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,...,394000.0,394000.0,394000.0,395000.0,395000.0,395000.0,631250.0,631250.0,631250.0,631250.0
Avg_price_sqft,990.243902,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,...,289.804469,289.804469,289.804469,204.643597,204.643597,204.643597,376.860294,376.860294,376.860294,376.860294

In [27]:
md.T

,0,1,2,3,4,5,6,7,8,9,...,425,426,427,428,429,430,431,432,433,434
School ID,02M260,06M211,01M539,02M294,02M308,02M545,01M292,01M696,02M305,01M509,...,28Q690,29Q327,27Q400,27Q260,27Q309,27Q302,27Q324,27Q262,27Q351,27Q323
School Name,Clinton School Writers and Artists,Inwood Early College for Health and Informatio...,"New Explorations into Science, Technology and ...",Essex Street Academy,Lower Manhattan Arts Academy,High School for Dual Language and Asian Studies,Henry Street School for International Studies,Bard High School Early College,Urban Assembly Academy of Government and Law,Marta Valle High School,...,High School for Law Enforcement and Public Safety,Eagle Academy for Young Men III,August Martin High School,Frederick Douglass Academy VI High School,Academy of Medical Technology (College Board),"Queens High School for Information, Research, ...",Rockaway Park High School for Environmental Su...,Channel View School for Research,Rockaway Collegiate High School,Scholars' Academy
Borough,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens
Building Code,M933,M052,M022,M445,M445,M445,M056,M097,M445,M025,...,Q690,Q633,Q400,Q465,Q465,Q465,Q410,Q410,Q410,Q180
Street Address,425 West 33rd Street,650 Academy Street,111 Columbia Street,350 Grand Street,350 Grand Street,350 Grand Street,220 Henry Street,525 East Houston Street,350 Grand Street,145 Stanton Street,...,116-25 Guy R Brewer Boulevard,171-10 Linden Boulevard,156-10 Baisley Boulevard,8-21 Bay 25th Street,8-21 Bay 25th Street,8-21 Bay 25th Street,100-00 Beach Channel Drive,100-00 Beach Channel Drive,100-00 Beach Channel Drive,320 Beach 104th Street
City,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Jamaica,Jamaica,Jamaica,Far Rockaway,Far Rockaway,Far Rockaway,Rockaway Park,Rockaway Park,Rockaway Park,Rockaway Park
State,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY,...,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY
Zip Code,10001,10002,10002,10002,10002,10002,10002,10002,10002,10002,...,11434,11434,11434,11691,11691,11691,11694,11694,11694,11694
Latitude,40.75321,40.86605,40.71873,40.71687,40.71687,40.71687,40.71376,40.71896,40.71687,40.72057,...,40.68618,40.69167,40.67553,40.60199,40.60199,40.60199,40.58601,40.58601,40.58601,40.58413
Longitude,-73.99786,-73.92486,-73.97943,-73.98953,-73.98953,-73.98953,-73.98526,-73.97607,-73.98953,-73.98567,...,-73.78408,-73.77903,-73.78343,-73.76283,-73.76283,-73.76283,-73.82309,-73.82309,-73.82309,-73.82568
Phone Number,212-695-9114,718-935-3660,212-677-5190,212-475-4773,212-505-0143,212-475-4097,212-406-9411,212-995-8479,212-505-0745,212-473-8152,...,718-977-4800,718-480-2600,718-528-2920,718-471-2154,718-471-3571,718-868-2978,718-734-3280,718-634-1970,718-734-3290,718-474-6918
Start Time,NaN,8:30 AM,8:15 AM,8:00 AM,8:30 AM,8:00 AM,8:30 AM,9:00 AM,8:32 AM,8:00 AM,...,8:00 AM,8:45 AM,8:00 AM,7:45 AM,8:00 AM,7:45 AM,8:45 AM,8:15 AM,8:30 AM,8:45 AM
End Time,NaN,3:00 PM,4:00 PM,2:45 PM,3:00 PM,3:35 PM,3:30 PM,3:50 PM,3:45 PM,3:30 PM,...,3:00 PM,4:45 PM,3:30 PM,2:05 PM,3:15 PM,4:10 PM,3:30 PM,3:04 PM,4:20 PM,3:00 PM
Student Enrollment,NaN,87.0,1735.0,358.0,383.0,416.0,255.0,545.0,329.0,363.0,...,604.0,428.0,679.0,409.0,637.0,381.0,368.0,683.0,397.0,1302.0
Percent White,NaN,3.4%,28.6%,11.7%,3.1%,1.7%,3.9%,45.3%,2.7%,2.5%,...,1.8%,1.8%,1.5%,0.7%,2.7%,2.1%,14.7%,10.7%,3.8%,34.7%
Percent Black,NaN,21.8%,13.3%,38.5%,28.2%,3.1%,24.4%,17.2%,41.9%,39.9%,...,66.4%,86.3%,75.4%,59.7%,50.1%,49.1%,46.7%,53.2%,52.6%,22.7%
Percent Hispanic,NaN,67.8%,18.0%,41.3%,56.9%,5.5%,56.6%,18.7%,49.2%,51.2%,...,18.9%,5.4%,13.0%,37.9%,37.7%,43.6%,30.2%,29.1%,33.5%,19.6%
Percent Asian,NaN,4.6%,38.5%,5.9%,8.6%,88.9%,13.2%,17.1%,5.8%,5.8%,...,10.4%,0.6%,7.5%,1.5%,6.6%,4.2%,3.5%,6.0%,5.0%,21.4%
Average Score (SAT Math),NaN,NaN,657.0,395.0,418.0,613.0,410.0,634.0,389.0,438.0,...,410.0,NaN,366.0,410.0,422.0,372.0,357.0,427.0,399.0,588.0
Average Score (SAT Reading),NaN,NaN,601.0,411.0,428.0,453.0,406.0,641.0,395.0,413.0,...,431.0,NaN,372.0,418.0,424.0,362.0,381.0,430.0,403.0,560.0
Average Score (SAT Writing),NaN,NaN,601.0,387.0,415.0,463.0,381.0,639.0,381.0,394.0,...,409.0,NaN,364.0,407.0,415.0,352.0,376.0,423.0,405.0,568.0
Percent Tested,NaN,NaN,91.0%,78.9%,65.1%,95.9%,59.7%,70.8%,80.8%,35.6%,...,56.6%,NaN,26.3%,30.1%,67.6%,44.6%,38.5%,76.6%,46.5%,99.2%
Avg total income,155.101676,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,...,39.71418,39.71418,39.71418,37.844035,37.844035,37.844035,91.24427,91.24427,91.24427,91.24427
TOTAL UNITS,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0
GROSS SQUARE FEET,19453.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,...,1378.0,1378.0,1378.0,2080.0,2080.0,2080.0,2115.0,2115.0,2115.0,2115.0
SALE PRICE,1750000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,...,394000.0,394000.0,394000.0,395000.0,395000.0,395000.0,631250.0,631250.0,631250.0,631250.0
Avg_price_sqft,990.243902,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,...,289.804469,289.804469,289.804469,204.643597,204.643597,204.643597,376.860294,376.860294,376.860294,376.860294

In [28]:
Crime_Data = pd.read_csv('/Users/chrislele/Downloads/NYPD_Complaint_Data_Current_YTD.csv')

In [29]:
ST_ratio = pd.read_csv('/Users/chrislele/Downloads/2015_-_2016_Final_Class_Size_Report_Pupil-to-Teacher_Ratio__PTR_.csv')

In [30]:
ST_ratio.T

,0,1,2,3,4,5,6,7,8,9,...,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570
DBN,15K001,12X691,11X567,09X555,12X536,12X531,11X483,11X481,12X463,12X458,...,21K344,21K337,14K322,13K265,20K227,20K223,32K168,17K122,14K071,18K068
School Name,P.S. 001 THE BERGEN,BRONX LITTLE SCHOOL,LINDEN TREE ELEMENTARY SCHOOL,MOUNT EDEN CHILDREN'S ACADEMY,PS 536,ARCHER ELEMENTARY SCHOOL,P.S. 483,P.S. 481,URBAN SCHOLARS COMMUNITY SCHOOL,SAMARA COMMUNITY SCHOOL,...,RACHEL CARSON HIGH SCHOOL FOR COASTAL STUDIES,INTERNATIONAL HIGH SCHOOL AT LAFAYETTE,FOUNDATIONS ACADEMY,DR. SUSAN S. MCKINNEY SECONDARY SCHOOL OF THE ...,J.H.S. 227 EDWARD B. SHALLOW,J.H.S. 223 THE MONTAUK,THE BROOKLYN SCHOOL FOR MATH AND RESEARCH,PATHWAYS IN TECHNOLOGY EARLY COLLEGE HIGH SCHO...,JUAN MOREL CAMPOS SECONDARY SCHOOL,I.S. 068 ISAAC BILDERSEE
School Pupil-Teacher Ratio,13.4,12.0,16.9,18.1,14.8,13.7,14.3,14.1,13.8,19.0,...,16.6,15.2,5.5,13.6,16.6,14.9,13.6,19.8,10.7,10.2

In [31]:
md.T

,0,1,2,3,4,5,6,7,8,9,...,425,426,427,428,429,430,431,432,433,434
School ID,02M260,06M211,01M539,02M294,02M308,02M545,01M292,01M696,02M305,01M509,...,28Q690,29Q327,27Q400,27Q260,27Q309,27Q302,27Q324,27Q262,27Q351,27Q323
School Name,Clinton School Writers and Artists,Inwood Early College for Health and Informatio...,"New Explorations into Science, Technology and ...",Essex Street Academy,Lower Manhattan Arts Academy,High School for Dual Language and Asian Studies,Henry Street School for International Studies,Bard High School Early College,Urban Assembly Academy of Government and Law,Marta Valle High School,...,High School for Law Enforcement and Public Safety,Eagle Academy for Young Men III,August Martin High School,Frederick Douglass Academy VI High School,Academy of Medical Technology (College Board),"Queens High School for Information, Research, ...",Rockaway Park High School for Environmental Su...,Channel View School for Research,Rockaway Collegiate High School,Scholars' Academy
Borough,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens
Building Code,M933,M052,M022,M445,M445,M445,M056,M097,M445,M025,...,Q690,Q633,Q400,Q465,Q465,Q465,Q410,Q410,Q410,Q180
Street Address,425 West 33rd Street,650 Academy Street,111 Columbia Street,350 Grand Street,350 Grand Street,350 Grand Street,220 Henry Street,525 East Houston Street,350 Grand Street,145 Stanton Street,...,116-25 Guy R Brewer Boulevard,171-10 Linden Boulevard,156-10 Baisley Boulevard,8-21 Bay 25th Street,8-21 Bay 25th Street,8-21 Bay 25th Street,100-00 Beach Channel Drive,100-00 Beach Channel Drive,100-00 Beach Channel Drive,320 Beach 104th Street
City,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Jamaica,Jamaica,Jamaica,Far Rockaway,Far Rockaway,Far Rockaway,Rockaway Park,Rockaway Park,Rockaway Park,Rockaway Park
State,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY,...,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY
Zip Code,10001,10002,10002,10002,10002,10002,10002,10002,10002,10002,...,11434,11434,11434,11691,11691,11691,11694,11694,11694,11694
Latitude,40.75321,40.86605,40.71873,40.71687,40.71687,40.71687,40.71376,40.71896,40.71687,40.72057,...,40.68618,40.69167,40.67553,40.60199,40.60199,40.60199,40.58601,40.58601,40.58601,40.58413
Longitude,-73.99786,-73.92486,-73.97943,-73.98953,-73.98953,-73.98953,-73.98526,-73.97607,-73.98953,-73.98567,...,-73.78408,-73.77903,-73.78343,-73.76283,-73.76283,-73.76283,-73.82309,-73.82309,-73.82309,-73.82568
Phone Number,212-695-9114,718-935-3660,212-677-5190,212-475-4773,212-505-0143,212-475-4097,212-406-9411,212-995-8479,212-505-0745,212-473-8152,...,718-977-4800,718-480-2600,718-528-2920,718-471-2154,718-471-3571,718-868-2978,718-734-3280,718-634-1970,718-734-3290,718-474-6918
Start Time,NaN,8:30 AM,8:15 AM,8:00 AM,8:30 AM,8:00 AM,8:30 AM,9:00 AM,8:32 AM,8:00 AM,...,8:00 AM,8:45 AM,8:00 AM,7:45 AM,8:00 AM,7:45 AM,8:45 AM,8:15 AM,8:30 AM,8:45 AM
End Time,NaN,3:00 PM,4:00 PM,2:45 PM,3:00 PM,3:35 PM,3:30 PM,3:50 PM,3:45 PM,3:30 PM,...,3:00 PM,4:45 PM,3:30 PM,2:05 PM,3:15 PM,4:10 PM,3:30 PM,3:04 PM,4:20 PM,3:00 PM
Student Enrollment,NaN,87.0,1735.0,358.0,383.0,416.0,255.0,545.0,329.0,363.0,...,604.0,428.0,679.0,409.0,637.0,381.0,368.0,683.0,397.0,1302.0
Percent White,NaN,3.4%,28.6%,11.7%,3.1%,1.7%,3.9%,45.3%,2.7%,2.5%,...,1.8%,1.8%,1.5%,0.7%,2.7%,2.1%,14.7%,10.7%,3.8%,34.7%
Percent Black,NaN,21.8%,13.3%,38.5%,28.2%,3.1%,24.4%,17.2%,41.9%,39.9%,...,66.4%,86.3%,75.4%,59.7%,50.1%,49.1%,46.7%,53.2%,52.6%,22.7%
Percent Hispanic,NaN,67.8%,18.0%,41.3%,56.9%,5.5%,56.6%,18.7%,49.2%,51.2%,...,18.9%,5.4%,13.0%,37.9%,37.7%,43.6%,30.2%,29.1%,33.5%,19.6%
Percent Asian,NaN,4.6%,38.5%,5.9%,8.6%,88.9%,13.2%,17.1%,5.8%,5.8%,...,10.4%,0.6%,7.5%,1.5%,6.6%,4.2%,3.5%,6.0%,5.0%,21.4%
Average Score (SAT Math),NaN,NaN,657.0,395.0,418.0,613.0,410.0,634.0,389.0,438.0,...,410.0,NaN,366.0,410.0,422.0,372.0,357.0,427.0,399.0,588.0
Average Score (SAT Reading),NaN,NaN,601.0,411.0,428.0,453.0,406.0,641.0,395.0,413.0,...,431.0,NaN,372.0,418.0,424.0,362.0,381.0,430.0,403.0,560.0
Average Score (SAT Writing),NaN,NaN,601.0,387.0,415.0,463.0,381.0,639.0,381.0,394.0,...,409.0,NaN,364.0,407.0,415.0,352.0,376.0,423.0,405.0,568.0
Percent Tested,NaN,NaN,91.0%,78.9%,65.1%,95.9%,59.7%,70.8%,80.8%,35.6%,...,56.6%,NaN,26.3%,30.1%,67.6%,44.6%,38.5%,76.6%,46.5%,99.2%
Avg total income,155.101676,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,...,39.71418,39.71418,39.71418,37.844035,37.844035,37.844035,91.24427,91.24427,91.24427,91.24427
TOTAL UNITS,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0
GROSS SQUARE FEET,19453.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,...,1378.0,1378.0,1378.0,2080.0,2080.0,2080.0,2115.0,2115.0,2115.0,2115.0
SALE PRICE,1750000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,...,394000.0,394000.0,394000.0,395000.0,395000.0,395000.0,631250.0,631250.0,631250.0,631250.0
Avg_price_sqft,990.243902,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,...,289.804469,289.804469,289.804469,204.643597,204.643597,204.643597,376.860294,376.860294,376.860294,376.860294

In [32]:
ST_ratio.columns

Index(['DBN', 'School Name', 'School Pupil-Teacher Ratio'], dtype='object')

In [33]:
md['School Name'] = md['School Name'].apply(lambda x: x.upper())

In [34]:
# Assuming 'ST_ratio' is the DataFrame containing the 'School Pupil-Teacher Ratio' column
md_merged_data = md.merge(ST_ratio[['School Name', 'School Pupil-Teacher Ratio']], on='School Name', how='left')

In [35]:
df_unmatched = pd.DataFrame(md_merged_data[md_merged_data['School Pupil-Teacher Ratio'].isnull()]['School Name'].unique())

In [36]:
df_unmatched = df_unmatched.rename(columns={0: 'School Name'})
df_unmatched['New Name'] = ''
df_unmatched

                                          School Name New Name
0                  CLINTON SCHOOL WRITERS AND ARTISTS
1        URBAN ASSEMBLY ACADEMY OF GOVERNMENT AND LAW
2              HIGH SCHOOL FOR LANGUAGE AND DIPLOMACY
3   URBAN ASSEMBLY SCHOOL OF BUSINESS FOR YOUNG WOMEN
4   47 AMERICAN SIGN LANGUAGE AND ENGLISH SECONDAR...
..                                                ...      ...
85  QUEENS HIGH SCHOOL OF TEACHING, LIBERAL ARTS, ...
86          YOUNG WOMEN'S LEADERSHIP SCHOOL IN QUEENS
87                  QUEENS COLLEGIATE (COLLEGE BOARD)
88                  HILLSIDE ARTS AND LETTERS ACADEMY
89      ACADEMY OF MEDICAL TECHNOLOGY (COLLEGE BOARD)

[90 rows x 2 columns]

In [37]:
df_unmatched.to_csv('lookup_names_missing.csv')

In [38]:
md_merged_data.T

,0,1,2,3,4,5,6,7,8,9,...,425,426,427,428,429,430,431,432,433,434
School ID,02M260,06M211,01M539,02M294,02M308,02M545,01M292,01M696,02M305,01M509,...,28Q690,29Q327,27Q400,27Q260,27Q309,27Q302,27Q324,27Q262,27Q351,27Q323
School Name,CLINTON SCHOOL WRITERS AND ARTISTS,INWOOD EARLY COLLEGE FOR HEALTH AND INFORMATIO...,"NEW EXPLORATIONS INTO SCIENCE, TECHNOLOGY AND ...",ESSEX STREET ACADEMY,LOWER MANHATTAN ARTS ACADEMY,HIGH SCHOOL FOR DUAL LANGUAGE AND ASIAN STUDIES,HENRY STREET SCHOOL FOR INTERNATIONAL STUDIES,BARD HIGH SCHOOL EARLY COLLEGE,URBAN ASSEMBLY ACADEMY OF GOVERNMENT AND LAW,MARTA VALLE HIGH SCHOOL,...,HIGH SCHOOL FOR LAW ENFORCEMENT AND PUBLIC SAFETY,EAGLE ACADEMY FOR YOUNG MEN III,AUGUST MARTIN HIGH SCHOOL,FREDERICK DOUGLASS ACADEMY VI HIGH SCHOOL,ACADEMY OF MEDICAL TECHNOLOGY (COLLEGE BOARD),"QUEENS HIGH SCHOOL FOR INFORMATION, RESEARCH, ...",ROCKAWAY PARK HIGH SCHOOL FOR ENVIRONMENTAL SU...,CHANNEL VIEW SCHOOL FOR RESEARCH,ROCKAWAY COLLEGIATE HIGH SCHOOL,SCHOLARS' ACADEMY
Borough,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens,Queens
Building Code,M933,M052,M022,M445,M445,M445,M056,M097,M445,M025,...,Q690,Q633,Q400,Q465,Q465,Q465,Q410,Q410,Q410,Q180
Street Address,425 West 33rd Street,650 Academy Street,111 Columbia Street,350 Grand Street,350 Grand Street,350 Grand Street,220 Henry Street,525 East Houston Street,350 Grand Street,145 Stanton Street,...,116-25 Guy R Brewer Boulevard,171-10 Linden Boulevard,156-10 Baisley Boulevard,8-21 Bay 25th Street,8-21 Bay 25th Street,8-21 Bay 25th Street,100-00 Beach Channel Drive,100-00 Beach Channel Drive,100-00 Beach Channel Drive,320 Beach 104th Street
City,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,Manhattan,...,Jamaica,Jamaica,Jamaica,Far Rockaway,Far Rockaway,Far Rockaway,Rockaway Park,Rockaway Park,Rockaway Park,Rockaway Park
State,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY,...,NY,NY,NY,NY,NY,NY,NY,NY,NY,NY
Zip Code,10001,10002,10002,10002,10002,10002,10002,10002,10002,10002,...,11434,11434,11434,11691,11691,11691,11694,11694,11694,11694
Latitude,40.75321,40.86605,40.71873,40.71687,40.71687,40.71687,40.71376,40.71896,40.71687,40.72057,...,40.68618,40.69167,40.67553,40.60199,40.60199,40.60199,40.58601,40.58601,40.58601,40.58413
Longitude,-73.99786,-73.92486,-73.97943,-73.98953,-73.98953,-73.98953,-73.98526,-73.97607,-73.98953,-73.98567,...,-73.78408,-73.77903,-73.78343,-73.76283,-73.76283,-73.76283,-73.82309,-73.82309,-73.82309,-73.82568
Phone Number,212-695-9114,718-935-3660,212-677-5190,212-475-4773,212-505-0143,212-475-4097,212-406-9411,212-995-8479,212-505-0745,212-473-8152,...,718-977-4800,718-480-2600,718-528-2920,718-471-2154,718-471-3571,718-868-2978,718-734-3280,718-634-1970,718-734-3290,718-474-6918
Start Time,NaN,8:30 AM,8:15 AM,8:00 AM,8:30 AM,8:00 AM,8:30 AM,9:00 AM,8:32 AM,8:00 AM,...,8:00 AM,8:45 AM,8:00 AM,7:45 AM,8:00 AM,7:45 AM,8:45 AM,8:15 AM,8:30 AM,8:45 AM
End Time,NaN,3:00 PM,4:00 PM,2:45 PM,3:00 PM,3:35 PM,3:30 PM,3:50 PM,3:45 PM,3:30 PM,...,3:00 PM,4:45 PM,3:30 PM,2:05 PM,3:15 PM,4:10 PM,3:30 PM,3:04 PM,4:20 PM,3:00 PM
Student Enrollment,NaN,87.0,1735.0,358.0,383.0,416.0,255.0,545.0,329.0,363.0,...,604.0,428.0,679.0,409.0,637.0,381.0,368.0,683.0,397.0,1302.0
Percent White,NaN,3.4%,28.6%,11.7%,3.1%,1.7%,3.9%,45.3%,2.7%,2.5%,...,1.8%,1.8%,1.5%,0.7%,2.7%,2.1%,14.7%,10.7%,3.8%,34.7%
Percent Black,NaN,21.8%,13.3%,38.5%,28.2%,3.1%,24.4%,17.2%,41.9%,39.9%,...,66.4%,86.3%,75.4%,59.7%,50.1%,49.1%,46.7%,53.2%,52.6%,22.7%
Percent Hispanic,NaN,67.8%,18.0%,41.3%,56.9%,5.5%,56.6%,18.7%,49.2%,51.2%,...,18.9%,5.4%,13.0%,37.9%,37.7%,43.6%,30.2%,29.1%,33.5%,19.6%
Percent Asian,NaN,4.6%,38.5%,5.9%,8.6%,88.9%,13.2%,17.1%,5.8%,5.8%,...,10.4%,0.6%,7.5%,1.5%,6.6%,4.2%,3.5%,6.0%,5.0%,21.4%
Average Score (SAT Math),NaN,NaN,657.0,395.0,418.0,613.0,410.0,634.0,389.0,438.0,...,410.0,NaN,366.0,410.0,422.0,372.0,357.0,427.0,399.0,588.0
Average Score (SAT Reading),NaN,NaN,601.0,411.0,428.0,453.0,406.0,641.0,395.0,413.0,...,431.0,NaN,372.0,418.0,424.0,362.0,381.0,430.0,403.0,560.0
Average Score (SAT Writing),NaN,NaN,601.0,387.0,415.0,463.0,381.0,639.0,381.0,394.0,...,409.0,NaN,364.0,407.0,415.0,352.0,376.0,423.0,405.0,568.0
Percent Tested,NaN,NaN,91.0%,78.9%,65.1%,95.9%,59.7%,70.8%,80.8%,35.6%,...,56.6%,NaN,26.3%,30.1%,67.6%,44.6%,38.5%,76.6%,46.5%,99.2%
Avg total income,155.101676,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,46.846786,...,39.71418,39.71418,39.71418,37.844035,37.844035,37.844035,91.24427,91.24427,91.24427,91.24427
TOTAL UNITS,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0
GROSS SQUARE FEET,19453.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,10230.0,...,1378.0,1378.0,1378.0,2080.0,2080.0,2080.0,2115.0,2115.0,2115.0,2115.0
SALE PRICE,1750000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,845000.0,...,394000.0,394000.0,394000.0,395000.0,395000.0,395000.0,631250.0,631250.0,631250.0,631250.0
Avg_price_sqft,990.243902,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,1016.835017,...,289.804469,289.804469,289.804469,204.643597,204.643597,204.643597,376.860294,376.860294,376.860294,376.860294
School Pupil-Teacher Ratio,NaN,11.9,19.0,13.8,13.4,16.6,8.9,17.5,NaN,10.9,...,20.5,13.0,11.0,15.6,NaN,15.1,14.2,13.8,13.8,20.2

In [39]:
def find_school(word):
    return ST_ratio[ST_ratio['School Name'].apply(lambda x: word in x)]

find_school("ACADEMY OF MEDICAL TECHNOLOGY")

,DBN,School Name,School Pupil-Teacher Ratio
1276,27Q309,ACADEMY OF MEDICAL TECHNOLOGY: A COLLEGE BOARD...,12.8

In [40]:
Edited_File = pd.read_csv('/Users/chrislele/Downloads/lookup_names_missing.csv')

In [41]:
df_unmatched['School Name'].update(Edited_File['School Name'])
print(df_unmatched['School Name'].head())

0                   CLINTON SCHOOL WRITERS AND ARTISTS
1         URBAN ASSEMBLY ACADEMY OF GOVERNMENT AND LAW
2               HIGH SCHOOL FOR LANGUAGE AND DIPLOMACY
3    URBAN ASSEMBLY SCHOOL OF BUSINESS FOR YOUNG WOMEN
4    47 AMERICAN SIGN LANGUAGE AND ENGLISH SECONDAR...
Name: School Name, dtype: object

In [42]:
nan_count = df_unmatched['School Name'].isna().sum()
print("Number of NaN values in 'School Name' column: ", nan_count)

Number of NaN values in 'School Name' column:  0

In [43]:
df_unmatched.head(100)

                                          School Name New Name
0                  CLINTON SCHOOL WRITERS AND ARTISTS
1        URBAN ASSEMBLY ACADEMY OF GOVERNMENT AND LAW
2              HIGH SCHOOL FOR LANGUAGE AND DIPLOMACY
3   URBAN ASSEMBLY SCHOOL OF BUSINESS FOR YOUNG WOMEN
4   47 AMERICAN SIGN LANGUAGE AND ENGLISH SECONDAR...
..                                                ...      ...
85  QUEENS HIGH SCHOOL OF TEACHING, LIBERAL ARTS, ...
86          YOUNG WOMEN'S LEADERSHIP SCHOOL IN QUEENS
87                  QUEENS COLLEGIATE (COLLEGE BOARD)
88                  HILLSIDE ARTS AND LETTERS ACADEMY
89      ACADEMY OF MEDICAL TECHNOLOGY (COLLEGE BOARD)

[90 rows x 2 columns]

In [44]:
def find_school(word):
    return ST_ratio[ST_ratio['School Name'].apply(lambda x: word in x)]

find_school("NYC LAB SCHOOL FOR COLLABORATIVE STUDIES")

Empty DataFrame
Columns: [DBN, School Name, School Pupil-Teacher Ratio]
Index: []

In [45]:
print(df_unmatched.columns)

Index(['School Name', 'New Name'], dtype='object')

In [46]:
md_merged_data[(md_merged_data['Average Score (SAT Math)'].isnull())]

,School ID,School Name,Borough,Building Code,Street Address,City,State,Zip Code,Latitude,Longitude,...,Average Score (SAT Math),Average Score (SAT Reading),Average Score (SAT Writing),Percent Tested,Avg total income,TOTAL UNITS,GROSS SQUARE FEET,SALE PRICE,Avg_price_sqft,School Pupil-Teacher Ratio
0,02M260,CLINTON SCHOOL WRITERS AND ARTISTS,Manhattan,M933,425 West 33rd Street,Manhattan,NY,10001,40.75321,-73.99786,...,NaN,NaN,NaN,NaN,155.101676,1.0,19453.0,1750000.0,990.243902,NaN
1,06M211,INWOOD EARLY COLLEGE FOR HEALTH AND INFORMATIO...,Manhattan,M052,650 Academy Street,Manhattan,NY,10002,40.86605,-73.92486,...,NaN,NaN,NaN,NaN,46.846786,0.0,10230.0,845000.0,1016.835017,11.9
15,02M546,ACADEMY FOR SOFTWARE ENGINEERING,Manhattan,M460,40 Irving Place,Manhattan,NY,10003,40.73552,-73.98760,...,NaN,NaN,NaN,NaN,212.309032,0.0,7692.0,1225000.0,1103.710015,12.8
16,02M533,UNION SQUARE ACADEMY FOR HEALTH SCIENCES,Manhattan,M460,40 Irving Place,Manhattan,NY,10003,40.73552,-73.98760,...,NaN,NaN,NaN,NaN,212.309032,0.0,7692.0,1225000.0,1103.710015,13.7
28,02M047,47 AMERICAN SIGN LANGUAGE AND ENGLISH SECONDAR...,Manhattan,M047,223 East 23rd Street,Manhattan,NY,10010,40.73860,-73.98251,...,NaN,NaN,NaN,48.3%,201.070122,1.0,24011.5,1382455.5,1248.403296,NaN
31,02M422,QUEST TO LEARN,Manhattan,M440,351 West 18th Street,Manhattan,NY,10011,40.74289,-74.00213,...,NaN,NaN,NaN,NaN,247.751578,1.0,5653.0,1485000.0,1689.149194,12.4
33,02M534,HARVEST COLLEGIATE HIGH SCHOOL,Manhattan,M883,34 West 14th Street,Manhattan,NY,10011,40.73676,-73.99551,...,NaN,NaN,NaN,NaN,247.751578,1.0,5653.0,1485000.0,1689.149194,12.6
36,02M605,HUMANITIES PREPARATORY ACADEMY,Manhattan,M440,351 West 18th Street,Manhattan,NY,10011,40.74289,-74.00213,...,NaN,NaN,NaN,NaN,247.751578,1.0,5653.0,1485000.0,1689.149194,14.1
42,02M432,MURRAY HILL ACADEMY,Manhattan,M620,111 East 33rd Street,Manhattan,NY,10016,40.74611,-73.98101,...,NaN,NaN,NaN,NaN,284.625638,1.0,8510.0,882250.0,1028.298991,11.3
49,02M135,URBAN ASSEMBLY SCHOOL FOR EMERGENCY MANAGEMENT,Manhattan,M625,439 West 49th Street,Manhattan,NY,10019,40.76336,-73.99051,...,NaN,NaN,NaN,NaN,252.430785,1.0,112850.0,1007500.0,0.442180,NaN
62,03M859,SPECIAL MUSIC SCHOOL,Manhattan,M490,122 Amsterdam Avenue,Manhattan,NY,10023,40.77430,-73.98482,...,NaN,NaN,NaN,NaN,320.408702,0.0,7243.0,1040000.0,961.337031,14.0
77,04M372,ESPERANZA PREPARATORY ACADEMY,Manhattan,M117,240 East 109th Street,Manhattan,NY,10029,40.79307,-73.94236,...,NaN,NaN,NaN,NaN,50.632099,1.0,9037.5,960000.0,504.568577,10.1
85,06M423,HIGH SCHOOL FOR EXCELLENCE AND INNOVATION,Manhattan,M052,650 Academy Street,Manhattan,NY,10034,40.86605,-73.92486,...,NaN,NaN,NaN,NaN,38.079990,0.0,22805.0,405000.0,318.985215,10.5
86,05M157,URBAN ASSEMBLY SCHOOL FOR GLOBAL COMMERCE,Manhattan,M501,2005 Madison Avenue,Manhattan,NY,10035,40.80734,-73.93943,...,NaN,NaN,NaN,NaN,39.684766,2.0,5167.0,1280000.0,496.134838,NaN
91,02M280,MANHATTAN EARLY COLLEGE SCHOOL FOR ADVERTISING,Manhattan,M520,411 Pearl Street,Manhattan,NY,10038,40.71068,-74.00081,...,NaN,NaN,NaN,NaN,117.597561,1.0,45159.5,997000.0,596.159173,13.1
93,02M282,URBAN ASSEMBLY MAKER ACADEMY,Manhattan,M520,411 Pearl Street,Manhattan,NY,10038,40.70934,-74.00530,...,NaN,NaN,NaN,NaN,117.597561,1.0,45159.5,997000.0,596.159173,13.0
94,02M139,STEPHEN T. MATHER BUILDING ARTS AND CRAFTSMANS...,Manhattan,M520,411 Pearl Street,Manhattan,NY,10038,40.71068,-74.00081,...,NaN,NaN,NaN,NaN,117.597561,1.0,45159.5,997000.0,596.159173,NaN
116,07X522,BRONX DESIGN AND CONSTRUCTION ACADEMY,Bronx,X600,333 East 151st Street,Bronx,NY,10451,40.81825,-73.91974,...,NaN,NaN,NaN,0.8%,29.320431,0.0,0.0,215000.0,inf,13.1
125,09X327,COMPREHENSIVE MODEL SCHOOL PROJECT,Bronx,X240,1501 Jerome Avenue,Bronx,NY,10452,40.84241,-73.91616,...,NaN,NaN,NaN,NaN,24.778897,2.0,2610.0,195000.0,209.666667,NaN
127,07X223,LABORATORY SCHOOL OF FINANCE AND TECHNOLOGY,Bronx,X149,360 East 145th Street,Bronx,NY,10454,40.81401,-73.92084,...,NaN,NaN,NaN,NaN,24.148292,2.0,2679.0,530000.0,221.217105,NaN
130,07X520,FOREIGN LANGUAGE ACADEMY OF GLOBAL STUDIES,Bronx,X155,470 Jackson Avenue,Bronx,NY,10455,40.81114,-73.90979,...,NaN,NaN,NaN,32.6%,25.437624,2.0,2280.0,350000.0,206.781520,6.2
132,07X259,"HERO HIGH (HEALTH, EDUCATION, AND RESEARCH OCC...",Bronx,X655,455 Southern Boulevard,Bronx,NY,10455,40.81041,-73.90680,...,NaN,NaN,NaN,NaN,25.437624,2.0,2280.0,350000.0,206.781520,NaN
137,08X559,SCHOOL FOR TOURISM AND HOSPITALITY,Bronx,X650,900 Tinton Avenue,Bronx,NY,10456,40.82189,-73.90344,...,NaN,NaN,NaN,NaN,23.858969,3.0,2916.5,256000.0,132.147606,10.6
146,09X564,CLAREMONT INTERNATIONAL HIGH SCHOOL,Bronx,X410,240 East 172nd Street,Bronx,NY,10457,40.84037,-73.91084,...,NaN,NaN,NaN,NaN,24.068618,2.0,2169.0,302500.0,176.704545,NaN
150,09X276,LEADERSHIP INSTITUTE,Bronx,X004,1701 Fulton Avenue,Bronx,NY,10457,40.84127,-73.89798,...,NaN,NaN,NaN,23.5%,24.068618,2.0,2169.0,302500.0,176.704545,10.8
151,09X350,NEW DIRECTIONS SECONDARY SCHOOL,Bronx,X410,240 East 172nd Street,Bronx,NY,10457,40.84037,-73.91084,...,NaN,NaN,NaN,NaN,24.068618,2.0,2169.0,302500.0,176.704545,10.4
160,10X524,CROTONA INTERNATIONAL HIGH SCHOOL,Bronx,X660,2474 Crotona Avenue,Bronx,NY,10458,40.85592,-73.88258,...,NaN,NaN,NaN,0.0%,26.238110,2.0,2374.5,250000.0,164.705882,12.9
162,10X264,BRONX ACADEMY FOR SOFTWARE ENGINEERING (BASE),Bronx,X660,2474 Crotona Avenue,Bronx,NY,10458,40.85592,-73.88258,...,NaN,NaN,NaN,NaN,26.238110,2.0,2374.5,250000.0,164.705882,12.6
165,10X565,HIGH SCHOOL FOR ENERGY AND TECHNOLOGY,Bronx,X660,2474 Crotona Avenue,Bronx,NY,10458,40.85592,-73.88258,...,NaN,NaN,NaN,NaN,26.238110,2.0,2374.5,250000.0,164.705882,12.6
179,08X348,SCHUYLERVILLE PREPARATORY HIGH SCHOOL,Bronx,X405,3000 East Tremont Avenue,Bronx,NY,10461,40.84051,-73.83812,...,NaN,NaN,NaN,NaN,47.376135,2.0,1920.0,371500.0,210.905350,13.5
181,08X558,WESTCHESTER SQUARE ACADEMY,Bronx,X405,3000 East Tremont Avenue,Bronx,NY,10461,40.84051,-73.83812,...,NaN,NaN,NaN,NaN,47.376135,2.0,1920.0,371500.0,210.905350,13.8
182,08X320,PELHAM LAB HIGH SCHOOL,Bronx,X405,3000 East Tremont Avenue,Bronx,NY,10461,40.84051,-73.83812,...,NaN,NaN,NaN,NaN,47.376135,2.0,1920.0,371500.0,210.905350,13.3
184,08X349,BRONX RIVER HIGH SCHOOL,Bronx,X405,3000 East Tremont Avenue,Bronx,NY,10461,40.84051,-73.83812,...,NaN,NaN,NaN,NaN,47.376135,2.0,1920.0,371500.0,210.905350,13.3
206,10X353,WORLD VIEW HIGH SCHOOL,Bronx,X440,100 West Mosholu Parkway South,Bronx,NY,10468,40.88008,-73.88590,...,NaN,NaN,NaN,NaN,27.030448,1.0,1519.5,137500.0,285.779607,10.8
211,10X351,BRONX COLLABORATIVE HIGH SCHOOL,Bronx,X440,100 West Mosholu Parkway South,Bronx,NY,10468,40.88008,-73.88590,...,NaN,NaN,NaN,NaN,27.030448,1.0,1519.5,137500.0,285.779607,13.2
226,08X432,BRONX BRIDGES HIGH SCHOOL,Bronx,X450,1980 Lafayette Avenue,Bronx,NY,10473,40.82230,-73.85596,...,NaN,NaN,NaN,1.2%,36.219546,2.0,1792.5,273500.0,192.542097,12.0
229,08X561,BRONX COMPASS HIGH SCHOOL,Bronx,X450,1980 Lafayette Avenue,Bronx,NY,10473,40.82230,-73.85596,...,NaN,NaN,NaN,NaN,36.219546,2.0,1792.5,273500.0,192.542097,11.4
250,30Q258,ENERGY TECH HIGH SCHOOL,Queens,Q204,36-41 28th Street,Astoria,NY,11106,40.75710,-73.93262,...,NaN,NaN,NaN,NaN,48.004701,1.0,2808.0,693710.0,552.608311,12.5
254,15K423,BROOKLYN FRONTIERS HIGH SCHOOL,Brooklyn,K520,112 Schermerhorn Street,Brooklyn,NY,11201,40.69020,-73.98927,...,NaN,NaN,NaN,NaN,175.123922,1.0,0.0,899450.0,inf,7.4
264,17K745,BROOKLYN INSTITUTE FOR LIBERAL ARTS,Brooklyn,K470,600 Kingston Avenue,Brooklyn,NY,11203,40.65952,-73.94255,...,NaN,NaN,NaN,NaN,36.807874,2.0,1704.0,300000.0,201.492537,14.0
278,14K322,FOUNDATIONS ACADEMY,Brooklyn,K033,70 Tompkins Avenue,Brooklyn,NY,11206,40.69706,-73.94668,...,NaN,NaN,NaN,18.9%,33.138808,1.0,998.5,432500.0,479.166667,5.5
279,14K614,YOUNG WOMEN'S LEADERSHIP SCHOOL OF BROOKLYN,Brooklyn,K147,325 Bushwick Avenue,Brooklyn,NY,11206,40.70560,-73.93948,...,NaN,NaN,NaN,0.0%,33.138808,1.0,998.5,432500.0,479.166667,12.5
291,19K764,URBAN ASSEMBLY SCHOOL FOR COLLABORATIVE HEALTH...,Brooklyn,K420,999 Jamaica Avenue,Brooklyn,NY,11208,40.69114,-73.86843,...,NaN,NaN,NaN,NaN,28.409986,2.0,2038.0,344000.0,183.333333,NaN
292,19K422,SPRING CREEK COMMUNITY SCHOOL,Brooklyn,K422,1065 Elton Street,Brooklyn,NY,11208,40.65752,-73.87478,...,NaN,NaN,NaN,NaN,28.409986,2.0,2038.0,344000.0,183.333333,11.7
311,16K765,NELSON MANDELA SCHOOL FOR SOCIAL JUSTICE,Brooklyn,K455,1700 Fulton Street,Brooklyn,NY,11213,40.67943,-73.93243,...,NaN,NaN,NaN,NaN,34.505269,2.0,2628.0,140000.0,174.237263,NaN
324,15K592,KHALIL GIBRAN INTERNATIONAL ACADEMY,Brooklyn,K806,362 Schermerhorn Street,Brooklyn,NY,11217,40.68674,-73.98023,...,NaN,NaN,NaN,NaN,107.585419,1.0,0.0,905000.0,inf,10.0
332,16K393,FREDERICK DOUGLASS ACADEMY IV SECONDARY SCHOOL,Brooklyn,K026,1014 Lafayette Avenue,Brooklyn,NY,11221,40.69213,-73.93150,...,NaN,NaN,NaN,42.9%,32.306276,2.0,2565.0,481650.0,257.575758,6.7
355,23K644,EAGLE ACADEMY FOR YOUNG MEN II,Brooklyn,K271,1137 Herkimer Street,Brooklyn,NY,11233,40.67783,-73.91582,...,NaN,NaN,NaN,0.0%,34.632030,2.0,2550.0,460000.0,240.625000,15.9
358,22K611,ORIGINS HIGH SCHOOL,Brooklyn,K495,3000 Avenue X,Brooklyn,NY,11235,40.59419,-73.93684,...,NaN,NaN,NaN,NaN,53.078979,1.0,0.0,201409.5,inf,14.4
368,32K168,BROOKLYN SCHOOL FOR MATH AND RESEARCH,Brooklyn,K480,400 Irving Avenue,Brooklyn,NY,11237,40.69696,-73.91082,...,NaN,NaN,NaN,0.0%,30.625892,3.0,3250.0,433890.0,290.697674,NaN
374,25Q241,QUEENS HIGH SCHOOL FOR LANGUAGE STUDIES,Queens,Q460,35-01 Union Street,Flushing,NY,11354,40.76524,-73.82786,...,NaN,NaN,NaN,NaN,36.064424,1.0,1939.0,727527.0,499.385681,13.2
375,25Q240,VERITAS ACADEMY,Queens,Q460,35-01 Union Street,Flushing,NY,11354,40.76524,-73.82786,...,NaN,NaN,NaN,NaN,36.064424,1.0,1939.0,727527.0,499.385681,16.4
390,24Q236,INTERNATIONAL HIGH SCHOOL FOR HEALTH SCIENCES,Queens,Q455,48-01 90th Street,Elmhurst,NY,11373,40.74121,-73.87473,...,NaN,NaN,NaN,NaN,31.764860,1.0,2218.0,432975.0,441.105725,13.3
393,28Q167,METROPOLITAN EXPEDITIONARY LEARNING SCHOOL,Queens,Q686,91-30 Metropolitan Avenue,Forest Hills,NY,11375,40.71044,-73.85063,...,NaN,NaN,NaN,NaN,85.221230,0.0,1817.5,371000.0,622.048611,12.6
396,29Q313,BENJAMIN FRANKLIN HIGH SCHOOL FOR FINANCE AND ...,Queens,Q490,207-01 116th Avenue,Cambria Heights,NY,11411,40.69781,-73.74586,...,NaN,NaN,NaN,NaN,48.062229,1.0,1250.0,410000.0,321.428571,NaN
398,29Q243,INSTITUTE FOR HEALTH PROFESSIONS AT CAMBRIA HE...,Queens,Q490,207-01 116th Avenue,Cambria Heights,NY,11411,40.69554,-73.73492,...,NaN,NaN,NaN,NaN,48.062229,1.0,1250.0,410000.0,321.428571,12.1
409,27Q334,EPIC HIGH SCHOOL NORTH,Queens,Q636,94-25 117th Street,South Richmond Hill,NY,11419,40.69288,-73.82931,...,NaN,NaN,NaN,NaN,32.108580,2.0,1600.0,500000.0,320.297321,NaN
410,27Q314,EPIC HIGH SCHOOL SOUTH,Queens,Q226,121-10 Rockaway Boulevard,Queens,NY,11420,40.67574,-73.81697,...,NaN,NaN,NaN,NaN,38.543939,1.0,1312.0,462000.0,342.902670,NaN
413,26Q315,BUSINESS TECHNOLOGY EARLY COLLEGE HIGH SCHOOL,Queens,Q435,230-17 Hillside Avenue,Queens Village,NY,11427,40.73282,-73.73965,...,NaN,NaN,NaN,NaN,54.788512,1.0,1530.0,472000.0,372.395833,14.6
426,29Q327,EAGLE ACADEMY FOR YOUNG MEN III,Queens,Q633,171-10 Linden Boulevard,Jamaica,NY,11434,40.69167,-73.77903,...,NaN,NaN,NaN,NaN,39.714180,1.0,1378.0,394000.0,289.804469,13.0

In [52]:
from geopy.geocoders import Nominatim

In [53]:
Crime_Data.T

,0,1,2,3,4,5,6,7,8,9,...,361730,361731,361732,361733,361734,361735,361736,361737,361738,361739
CMPLNT_NUM,736216184,294332956,852981427,369976063,117213771,535504374,457718282,169644942,814258815,589253624,...,251695287,479338031,969186688,825396418,593729461,582350583,258046495,640212578,496500431,256379572
CMPLNT_FR_DT,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,...,01/01/2015,01/01/2015,01/01/2015,01/01/2015,01/01/2015,01/01/2015,01/01/2015,01/01/2015,06/30/2014,12/31/2001
CMPLNT_FR_TM,23:25:00,23:16:00,23:00:00,23:00:00,23:00:00,22:55:00,22:51:00,22:48:00,22:45:00,22:45:00,...,07:40:00,06:30:00,04:45:00,04:30:00,04:30:00,03:50:00,01:25:00,00:30:00,12:00:00,16:00:00
CMPLNT_TO_DT,09/30/2016,09/30/2016,09/30/2016,NaN,09/30/2016,09/30/2016,NaN,09/30/2016,NaN,09/30/2016,...,01/01/2016,01/01/2015,01/01/2016,01/01/2016,01/01/2016,01/01/2016,01/01/2016,01/01/2016,12/29/2015,01/01/2016
CMPLNT_TO_TM,23:25:00,23:21:00,23:05:00,NaN,23:10:00,23:15:00,NaN,22:50:00,NaN,22:50:00,...,07:50:00,07:00:00,05:00:00,05:00:00,04:50:00,04:00:00,01:30:00,00:40:00,12:00:00,10:50:00
RPT_DT,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,09/30/2016,...,01/01/2016,01/01/2016,01/01/2016,01/01/2016,01/01/2016,01/01/2016,01/01/2016,01/01/2016,01/01/2016,01/01/2016
KY_CD,236,344,235,118,578,118,236,235,117,117,...,106,578,578,344,105,105,578,106,361,107
OFNS_DESC,DANGEROUS WEAPONS,ASSAULT 3 & RELATED OFFENSES,DANGEROUS DRUGS,DANGEROUS WEAPONS,HARRASSMENT 2,DANGEROUS WEAPONS,DANGEROUS WEAPONS,DANGEROUS DRUGS,DANGEROUS DRUGS,DANGEROUS DRUGS,...,FELONY ASSAULT,HARRASSMENT 2,HARRASSMENT 2,ASSAULT 3 & RELATED OFFENSES,ROBBERY,ROBBERY,HARRASSMENT 2,FELONY ASSAULT,OFF. AGNST PUB ORD SENSBLTY &,BURGLARY
PD_CD,782.0,101.0,567.0,793.0,637.0,792.0,782.0,511.0,568.0,501.0,...,109.0,637.0,637.0,101.0,382.0,399.0,638.0,109.0,639.0,213.0
PD_DESC,"WEAPONS, POSSESSION, ETC",ASSAULT 3,"MARIJUANA, POSSESSION 4 & 5",WEAPONS POSSESSION 3,"HARASSMENT,SUBD 1,CIVILIAN",WEAPONS POSSESSION 1 & 2,"WEAPONS, POSSESSION, ETC","CONTROLLED SUBSTANCE, POSSESSI","MARIJUANA, POSSESSION 1, 2 & 3","CONTROLLED SUBSTANCE,POSSESS.",...,"ASSAULT 2,1,UNCLASSIFIED","HARASSMENT,SUBD 1,CIVILIAN","HARASSMENT,SUBD 1,CIVILIAN",ASSAULT 3,"ROBBERY,NECKCHAIN/JEWELRY","ROBBERY,COMMERCIAL UNCLASSIFIED","HARASSMENT,SUBD 3,4,5","ASSAULT 2,1,UNCLASSIFIED",AGGRAVATED HARASSMENT 2,"BURGLARY,COMMERCIAL,NIGHT"
CRM_ATPT_CPTD_CD,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,...,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED
LAW_CAT_CD,MISDEMEANOR,MISDEMEANOR,MISDEMEANOR,FELONY,VIOLATION,FELONY,MISDEMEANOR,MISDEMEANOR,FELONY,FELONY,...,FELONY,VIOLATION,VIOLATION,MISDEMEANOR,FELONY,FELONY,VIOLATION,FELONY,MISDEMEANOR,FELONY
JURIS_DESC,N.Y. TRANSIT POLICE,N.Y. POLICE DEPT,N.Y. HOUSING POLICE,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. HOUSING POLICE,...,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. TRANSIT POLICE,N.Y. POLICE DEPT,N.Y. POLICE DEPT,N.Y. POLICE DEPT
BORO_NM,BRONX,BROOKLYN,BRONX,QUEENS,QUEENS,BROOKLYN,BRONX,MANHATTAN,MANHATTAN,BRONX,...,BROOKLYN,BROOKLYN,QUEENS,BRONX,QUEENS,MANHATTAN,BRONX,QUEENS,BRONX,BROOKLYN
ADDR_PCT_CD,42.0,71.0,43.0,103.0,110.0,75.0,49.0,25.0,33.0,43.0,...,75.0,83.0,109.0,41.0,109.0,30.0,41.0,109.0,50.0,84.0
LOC_OF_OCCUR_DESC,NaN,OPPOSITE OF,INSIDE,NaN,FRONT OF,NaN,FRONT OF,NaN,FRONT OF,FRONT OF,...,INSIDE,INSIDE,INSIDE,INSIDE,NaN,INSIDE,NaN,FRONT OF,INSIDE,INSIDE
PREM_TYP_DESC,TRANSIT - NYC SUBWAY,STREET,RESIDENCE - PUBLIC HOUSING,STREET,STREET,STREET,STREET,STREET,STREET,RESIDENCE - PUBLIC HOUSING,...,PUBLIC BUILDING,RESIDENCE - APT. HOUSE,RESIDENCE-HOUSE,RESIDENCE - APT. HOUSE,STREET,HOTEL/MOTEL,TRANSIT - NYC SUBWAY,BAR/NIGHT CLUB,RESIDENCE - APT. HOUSE,PUBLIC SCHOOL
PARKS_NM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HADEVELOPT,NaN,NaN,CASTLE HILL,NaN,NaN,NaN,NaN,NaN,NaN,BRONXDALE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
X_COORD_CD,1015308.0,997932.0,1025580.0,1038464.0,1016301.0,1016123.0,1021316.0,1001446.0,1000481.0,1021576.0,...,1015693.0,1009950.0,1038616.0,1013080.0,1032890.0,998372.0,1014468.0,1030529.0,1009735.0,989682.0
Y_COORD_CD,244373.0,180172.0,236918.0,192970.0,209428.0,180753.0,253601.0,234215.0,243059.0,240437.0,...,180982.0,192049.0,214409.0,240805.0,216576.0,240146.0,238156.0,214093.0,261272.0,188334.0
Latitude,40.837376,40.661205,40.816872,40.696177,40.741458,40.662753,40.862681,40.809533,40.83381,40.826549,...,40.663383,40.693778,40.755021,40.827591,40.761002,40.825818,40.820315,40.754199,40.883777,40.683617
Longitude,-73.887761,-73.950687,-73.850685,-73.804492,-73.884339,-73.885117,-73.865998,-73.937883,-73.941347,-73.865131,...,-73.886666,-73.907324,-73.803771,-73.895828,-73.824423,-73.948975,-73.890825,-73.832963,-73.907837,-73.980416
Lat_Lon,"(40.837376359, -73.887760929)","(40.661204871, -73.950686652)","(40.816872438, -73.850684927)","(40.696177006, -73.804492266)","(40.741458245, -73.884339073)","(40.662752793, -73.885117129)","(40.862681292, -73.86599763)","(40.809533401, -73.937882826)","(40.833809505, -73.941347389)","(40.826548914, -73.865130932)",...,"(40.663382884, -73.886665968)","(40.693777815, -73.907324243)","(40.755020782, -73.803770928)","(40.827590785, -73.895828025)","(40.761001984, -73.824422813)","(40.825817778, -73.948974825)","(40.820315396, -73.890824603)","(40.754199468, -73.832962523)","(40.883776851, -73.907836928)","(40.683616638, -73.980416007)"

In [54]:
Crime_Data.isnull()

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,False,False,False,True,True,False,False,False,False,False,...,False,True,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361735,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
361736,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,True,False,False,False,False,False
361737,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
361738,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
361739,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False

In [55]:
Crime_Data= Crime_Data.dropna(how='any',axis=0)

In [56]:
import os
import time
from geopy.geocoders import Nominatim
import pandas as pd

# Function to download a portion of the dataset
def download_dataset(start_index, end_index):
    # Code to download the dataset between start_index and end_index
    # ...

    # Simulating the dataset size
    dataset_size = end_index - start_index

    return dataset_size


# Constants
MAX_DOWNLOAD_SIZE = 1000  # Maximum dataset size in megabytes
TIME_INTERVAL_HOURS = 1  # Time interval between downloads in hours

# Create a geolocator object
geolocator = Nominatim(user_agent="my_app")

# Variables
start_index = 0
end_index = 100  # Initial portion to process

# Download the initial portion to measure the size
dataset_size = download_dataset(start_index, end_index)
print("Initial dataset size:", dataset_size, "MB")

# Calculate the number of repetitions needed
repetitions = int(MAX_DOWNLOAD_SIZE / dataset_size)
print("Number of repetitions needed:", repetitions)

# Set the time interval in seconds
time_interval_seconds = TIME_INTERVAL_HOURS * 3600

new_df= pd.DataFrame()
new_col= []


# Process the dataset in a loop
for i in range(repetitions):
    # Subset the data to the current portion
    subset = Crime_Data.iloc[start_index:end_index].copy()

    # Perform reverse geocoding for the subset
    #subset['Address'] = subset.apply(lambda row: geolocator.reverse("{}, {}".format(row['Latitude'], row['Longitude'])),
                                                                    #axis=1)
 
    subset = subset.reset_index(drop=True)
    for index, row in subset.iterrows():
         lat = row['Latitude']
         lang = row['Longitude']
         #subset.iloc[index,'Address'] = geolocator.reverse(f'{lat}, {lang}')
         new_val = geolocator.reverse(f'{lat}, {lang}')
         new_col.append(new_val)
                                            

    # Update the subset in the main dataset
    # Crime_Data.iloc[start_index:end_index] = subset
    
    new_df=pd.concat([new_df,subset],ignore_index=True)
                                     

    print("Processed dataset", i + 1)

    # Update the indices for the next iteration
    start_index = end_index
    end_index += 100  # Increase the portion size for the next iteration

    # Wait for the specified time interval
    time.sleep(time_interval_seconds)

# Save the updated Crime_Data to a file or any other destination
# Crime_Data.to_csv("updated_crime_data.csv", index=False)
new_df.to_csv("subset.csv")

Initial dataset size: 100 MB
Number of repetitions needed: 10
Processed dataset 1

KeyboardInterrupt:

In [57]:
subset["Address"] = new_col

subset.to_csv("New_csv_file.csv")

In [62]:
student_enroll = 'Student Enrollment'
column_info = merged_data[student_enroll].info()
print(column_info)

<class 'pandas.core.series.Series'>
Int64Index: 435 entries, 0 to 434
Series name: Student Enrollment
Non-Null Count  Dtype
--------------  -----
428 non-null    float64
dtypes: float64(1)
memory usage: 23.0 KB
None

In [64]:
merged_data.select_dtypes(object)

,School ID,School Name,Borough,Building Code,Street Address,City,State,Phone Number,Start Time,End Time,Percent White,Percent Black,Percent Hispanic,Percent Asian,Percent Tested
0,02M260,Clinton School Writers and Artists,Manhattan,M933,425 West 33rd Street,Manhattan,NY,212-695-9114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,06M211,Inwood Early College for Health and Informatio...,Manhattan,M052,650 Academy Street,Manhattan,NY,718-935-3660,8:30 AM,3:00 PM,3.4%,21.8%,67.8%,4.6%,NaN
2,01M539,"New Explorations into Science, Technology and ...",Manhattan,M022,111 Columbia Street,Manhattan,NY,212-677-5190,8:15 AM,4:00 PM,28.6%,13.3%,18.0%,38.5%,91.0%
3,02M294,Essex Street Academy,Manhattan,M445,350 Grand Street,Manhattan,NY,212-475-4773,8:00 AM,2:45 PM,11.7%,38.5%,41.3%,5.9%,78.9%
4,02M308,Lower Manhattan Arts Academy,Manhattan,M445,350 Grand Street,Manhattan,NY,212-505-0143,8:30 AM,3:00 PM,3.1%,28.2%,56.9%,8.6%,65.1%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,27Q302,"Queens High School for Information, Research, ...",Queens,Q465,8-21 Bay 25th Street,Far Rockaway,NY,718-868-2978,7:45 AM,4:10 PM,2.1%,49.1%,43.6%,4.2%,44.6%
431,27Q324,Rockaway Park High School for Environmental Su...,Queens,Q410,100-00 Beach Channel Drive,Rockaway Park,NY,718-734-3280,8:45 AM,3:30 PM,14.7%,46.7%,30.2%,3.5%,38.5%
432,27Q262,Channel View School for Research,Queens,Q410,100-00 Beach Channel Drive,Rockaway Park,NY,718-634-1970,8:15 AM,3:04 PM,10.7%,53.2%,29.1%,6.0%,76.6%
433,27Q351,Rockaway Collegiate High School,Queens,Q410,100-00 Beach Channel Drive,Rockaway Park,NY,718-734-3290,8:30 AM,4:20 PM,3.8%,52.6%,33.5%,5.0%,46.5%
434,27Q323,Scholars' Academy,Queens,Q180,320 Beach 104th Street,Rockaway Park,NY,718-474-6918,8:45 AM,3:00 PM,34.7%,22.7%,19.6%,21.4%,99.2%

In [65]:
merged_data[['School Name', 'Borough']].nunique

<bound method DataFrame.nunique of                                            School Name    Borough
0                   Clinton School Writers and Artists  Manhattan
1    Inwood Early College for Health and Informatio...  Manhattan
2    New Explorations into Science, Technology and ...  Manhattan
3                                 Essex Street Academy  Manhattan
4                         Lower Manhattan Arts Academy  Manhattan
..                                                 ...        ...
430  Queens High School for Information, Research, ...     Queens
431  Rockaway Park High School for Environmental Su...     Queens
432                   Channel View School for Research     Queens
433                    Rockaway Collegiate High School     Queens
434                                  Scholars' Academy     Queens

[435 rows x 2 columns]>

In [66]:
SAT_df = merged_data

In [ ]:
SAT_df.head()

In [ ]:
sns.catplot(x="Average Score (SAT Math)", y="Average Score (SAT Reading)", 
data=SAT_df, kind="point", 
hue="School Name")


# Show plot
plt.show()

In [ ]:
SAT_df['Average Score (SAT Math)'].plot.hist(bins=15)

In [ ]:
SAT_df['Average Score (SAT Math)']

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Histogram of SAT Math scores
plt.figure(figsize=(8, 6))
sns.histplot(SAT_df['Average Score (SAT Math)'])
plt.title('SAT Math Scores Distribution')
plt.xlabel('SAT Math Score')
plt.show()